name: char_type - Unity

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make -C 3_chartype/ test_char_type.c
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
